inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1

  UseCache: true
  MaxFilesInCache: 20000
  CacheRootDirectory: /tmp

  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - '**/squirrels.rake'
    - '**/testimonials.rake'

Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
